# pdf_summarizer_web_app/pdf_summarizer_web_app/settings.py

import os # This was added previously
from pathlib import Path # <--- Add this line

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

# ... rest of your settings ...

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

# ... rest of your settings ...

"""
Django settings for pdf_summarizer_web_app project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aeci3)kc6whyz9^x$-$li0w)4*et&_$9q+5v^_@lbs^i9s&9ym'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'summarizer_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdf_summarizer_web_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'summarizer_app', 'templates')], # <--- This is the crucial change
        'APP_DIRS': True, # Keep this as True, it helps find templates in app/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdf_summarizer_web_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# pdf_summarizer_web_app/pdf_summarizer_web_app/settings.py

# ... (other settings) ...

# Custom settings for PDF Summarizer
import os

# Path to Poppler's 'bin' folder (where pdftoppm.exe is located)
# IMPORTANT: Update this to your actual Poppler bin path!
POPPLER_PATH = r"C:\Users\shaha\Downloads\Release-24.08.0-0\poppler-24.08.0\Library\bin"

# Path to Tesseract's executable (tesseract.exe)
# IMPORTANT: Update this to your actual Tesseract.exe path!
TESSERACT_CMD = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

# Set TESSDATA_PREFIX environment variable for Tesseract
# This is crucial for Tesseract to find its language data
TESSDATA_PREFIX = r"C:\Program Files\Tesseract-OCR\tessdata"
os.environ['TESSDATA_PREFIX'] = TESSDATA_PREFIX

# Path to your existing pdf_summarizer_project folder
# This is where your text_extractor, summarizer, etc. modules are located
SUMMARIZER_CORE_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'pdf_summarizer_project'))
# Add this path to Python's system path so Django can import your modules
import sys
sys.path.insert(0, SUMMARIZER_CORE_PATH)